using CLauncher.Models;

namespace CLauncher.Services;

public sealed class ServerService
{
    public string ResolveServerDirectory(LauncherConfig config, string basePath)
    {
        return Path.Combine(basePath, config.InstallRoot, config.Server.Name);
    }

    public string GetServerJarPath(LauncherConfig config, string serverDirectory)
    {
        return Path.Combine(serverDirectory, config.Server.JarFileName);
    }

    public string BuildDownloadUrl(ServerConfig serverConfig, PaperBuildInfo? paperBuildInfo, string? vanillaUrl)
    {
        return serverConfig.Type.ToLowerInvariant() switch
        {
            "paper" => BuildPaperUrl(paperBuildInfo ?? throw new InvalidOperationException("Paper build info missing.")),
            "bukkit" => $"https://download.getbukkit.org/bukkit/bukkit-{serverConfig.Version}.jar",
            "craftbukkit" => $"https://download.getbukkit.org/craftbukkit/craftbukkit-{serverConfig.Version}.jar",
            "vanilla" => vanillaUrl ?? throw new InvalidOperationException("Vanilla server URL missing."),
            _ => throw new InvalidOperationException($"Unknown server type: {serverConfig.Type}")
        };
    }

    public void EnsureServerProperties(LauncherConfig config, string serverDirectory)
    {
        Directory.CreateDirectory(serverDirectory);
        var path = Path.Combine(serverDirectory, "server.properties");

        var properties = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["online-mode"] = config.Server.OnlineMode ? "true" : "false",
            ["server-port"] = config.Server.Port.ToString()
        };

        var existing = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (File.Exists(path))
        {
            foreach (var line in File.ReadAllLines(path))
            {
                if (string.IsNullOrWhiteSpace(line) || line.TrimStart().StartsWith("#", StringComparison.Ordinal))
                {
                    continue;
                }

                var split = line.Split('=', 2);
                if (split.Length == 2)
                {
                    existing[split[0].Trim()] = split[1].Trim();
                }
            }
        }

        foreach (var pair in properties)
        {
            existing[pair.Key] = pair.Value;
        }

        var lines = existing.Select(pair => $"{pair.Key}={pair.Value}");
        File.WriteAllLines(path, lines);
    }

    public void EnsureEula(ServerConfig config, string serverDirectory)
    {
        var path = Path.Combine(serverDirectory, "eula.txt");
        var value = config.AcceptEula ? "true" : "false";
        File.WriteAllText(path, $"# Generated by C_launcher\neula={value}\n");
    }

    private static string BuildPaperUrl(PaperBuildInfo buildInfo)
    {
        return $"https://api.papermc.io/v2/projects/paper/versions/{buildInfo.Version}/builds/{buildInfo.Build}/downloads/paper-{buildInfo.Version}-{buildInfo.Build}.jar";
    }
}
